/*
 * batester_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package api_pkg

import "batester_lib/configuration_pkg"

/*
 * Interface for the API_IMPL
 */
type API interface {
    GetBasicAuthTest () (string, error)
}

/*
 * Factory for the API interaface returning API_IMPL
 */
func NewAPI(config configuration_pkg.CONFIGURATION) *API_IMPL {
    client := new(API_IMPL)
    client.config = config
    return client
}