/**
 * BATesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const configuration = require("../lib/configuration");
const environments = require("../lib/Environments");

const testConfiguration = {
    ASSERT_PRECISION: 0.01,
    TEST_TIMEOUT: 100000
};

configuration.currentEnvironment = environments.TESTING;

configuration.BASEURI = 'http://localhost:3000';
configuration.basicAuthUserName = 'Zeeshan';
configuration.basicAuthPassword = 'bhai_99';

module.exports = testConfiguration;
