/*
 * batester_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for SuiteCodeEnum enum
 */
type SuiteCodeEnum int

/**
 * Value collection for SuiteCodeEnum enum
 */
const (
    SuiteCode_HEARTS SuiteCodeEnum = 1
    SuiteCode_SPADES = 2
    SuiteCode_CLUBS = 3
    SuiteCode_DIAMONDS = 4
)

func (r SuiteCodeEnum) MarshalJSON() ([]byte, error) { 
    s := SuiteCodeEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *SuiteCodeEnum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  SuiteCodeEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts SuiteCodeEnum to its int representation
 */
func SuiteCodeEnumToValue(suiteCodeEnum SuiteCodeEnum) int {
    switch suiteCodeEnum {
        case SuiteCode_HEARTS:
    		return 1		
        case SuiteCode_SPADES:
    		return 2		
        case SuiteCode_CLUBS:
    		return 3		
        case SuiteCode_DIAMONDS:
    		return 4		
        default:
        	return 1
    }
}

/**
 * Converts SuiteCodeEnum Array to its string Array representation
*/
func SuiteCodeEnumArrayToValue(suiteCodeEnum []SuiteCodeEnum) []int {
    convArray := make([]int,len( suiteCodeEnum))
    for i:=0; i<len(suiteCodeEnum);i++ {
        convArray[i] = SuiteCodeEnumToValue(suiteCodeEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func SuiteCodeEnumFromValue(value int) SuiteCodeEnum {
    switch value {
        case 1:
            return SuiteCode_HEARTS
        case 2:
            return SuiteCode_SPADES
        case 3:
            return SuiteCode_CLUBS
        case 4:
            return SuiteCode_DIAMONDS
        default:
            return SuiteCode_HEARTS
    }
}
