/**
 * BATesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

angular.module('BATesterLib')
    .factory('Configuration', ['APIHelper', 'Servers', 'Environments', Configuration]);

    function Configuration(APIHelper, Servers, Environments) {
        var environmentsMap = [],
            e = Environments, 
            s = Servers;
    
    
        environmentsMap[e.PRODUCTION] = [];
        environmentsMap[e.TESTING] = [];
    
        environmentsMap[e.PRODUCTION][s.MDEFAULT] = 'http://apimatic.hopto.org:{suites}';
        environmentsMap[e.PRODUCTION][s.AUTH_SERVER] = 'http://apimaticauth.hopto.org:3000';
        environmentsMap[e.TESTING][s.MDEFAULT] = 'http://localhost:3000';
        environmentsMap[e.TESTING][s.AUTH_SERVER] = 'http://apimaticauth.xhopto.org:3000';

        return {
            //The username to use with basic authentication
            //TODO: Replace the basicAuthUserName with an appropriate value
            basicAuthUserName : 'TODO: Replace',

            //The password to use with basic authentication
            //TODO: Replace the basicAuthPassword with an appropriate value
            basicAuthPassword : 'TODO: Replace',

            /**
             * port
             * @type {string}
             */
            port: '80',

            /**
             * suites
             * @type {SuiteCodeEnum}
             */
            suites: 1,

            /**
             * Current API environment
             * @type {string}
             */
            currentEnvironment: e.PRODUCTION,
    
            /**
             * Get base URI for a server in the current API environment
             * @param  {string|null} server Server name
             * @return {string}             Base URI for server
             */
            getBaseUri: function (server) {
                var url = environmentsMap[this.currentEnvironment][server || s.MDEFAULT];
                var urlParams = {
                        port: this.port,
                    suites: this.suites
                };
                return APIHelper.appendUrlWithTemplateParameters(url, urlParams);
            }
        };
    }

}(angular));
