/**
  * BATesterLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('BATesterLib')
    .factory('Environments', [EnvironmentsModel]);

    function EnvironmentsModel() {
        return {
            //TODO: Write general description for this element
            PRODUCTION: 'production',
    
            //TODO: Write general description for this element
            TESTING: 'testing'
        };
    }

}(angular));
