/**
  * BATesterLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('BATesterLib')
    .factory('Servers', [ServersModel]);

    function ServersModel() {
        return {
            //TODO: Write general description for this element
            MDEFAULT: 'default',
    
            //TODO: Write general description for this element
            AUTH_SERVER: 'auth server'
        };
    }

}(angular));
