/*
 * batester_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package BATesterClient

import(
	"batester_lib/configuration_pkg"
	"batester_lib/apiclient_pkg"
)


/*
 * Interface for the BATESTER_IMPL
 */
type BATESTER interface {
     APIClient()             apiclient_pkg.APICLIENT
     Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the BATESTER interaface returning BATESTER_IMPL
 */
func NewBATESTER(basicAuthUserName string, basicAuthPassword string) BATESTER {
    bATesterClient := new(BATESTER_IMPL)
    bATesterClient.config = configuration_pkg.NewCONFIGURATION()
    bATesterClient.config.SetBasicAuthUserName(basicAuthUserName)
    bATesterClient.config.SetBasicAuthPassword(basicAuthPassword)
    return bATesterClient
}
