/*
 * batester_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package BATesterClient

import(
	"batester_lib/configuration_pkg"
	"batester_lib/apiclient_pkg"
)
/*
 * Client structure as interface implementation
 */
type BATESTER_IMPL struct {
     apiclient apiclient_pkg.APICLIENT
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *BATESTER_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to APIClient controller
     * @return Returns the APIClient() instance
*/
func (me * BATESTER_IMPL) APIClient() apiclient_pkg.APICLIENT {
    if(me.apiclient) == nil {
        me.apiclient = apiclient_pkg.NewAPICLIENT(me.config)
    }
    return me.apiclient
}
