/*
 * BATesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.APIController;
const SuiteCodeEnum = testerlib.SuiteCodeEnum;


describe("APIController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Todo Add description for test testBasicAuthTest
     */
    it("should testBasicAuthTest response", function testBasicAuthTestTest(done) {
        controller.getBasicAuthTest(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            assert.isNotNull(response);
            assert.equal('You\'ve passed the test!', context.response.body);
            done();
        });
    });
});
