# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

require_relative 'controller_test_base'

class APIControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.client
  end

  # Todo: Add description for test test_basic_auth_test
  def test_basic_auth_test()

    # Perform the API call through the SDK function
    result = self.class.controller.get_basic_auth_test()

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)

    # Test whether the captured response is as we expected
    assert_not_nil(result)
    assert_equal('You\'ve passed the test!', @response_catcher.response.raw_body)
  end

end
