/**
  * BATesterLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('BATesterLib')
    .factory('SuiteCodeEnum', [SuiteCodeEnumModel]);

    function SuiteCodeEnumModel() {
        return {
            //TODO: Write general description for this element
            HEARTS: 1,
    
            //TODO: Write general description for this element
            SPADES: 2,
    
            //TODO: Write general description for this element
            CLUBS: 3,
    
            //TODO: Write general description for this element
            DIAMONDS: 4
        };
    }

}(angular));
