/*
 * BATesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.hopto.apimatic;

import java.util.EnumMap;
import java.util.HashMap;
import java.util.Map;

import org.hopto.apimatic.models.*;

public class Configuration {
    //The username to use with basic authentication
    //TODO: Replace the basicAuthUserName with an appropriate value
    public static String basicAuthUserName = "TODO: Replace";

    //The password to use with basic authentication
    //TODO: Replace the basicAuthPassword with an appropriate value
    public static String basicAuthPassword = "TODO: Replace";

    /**
     * Current API environment
     */
    public static Environments environment = Environments.PRODUCTION;

    /**
     *  port value
     */
    public static String port = "80";

    /**
     *  suites value
     */
    public static SuiteCodeEnum suites = SuiteCodeEnum.HEARTS;

    /**
     * Get base URI by current environment
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public static String getBaseUri(Servers server) {
        StringBuilder baseUrl = new StringBuilder(environmentsMap.get(Configuration.environment).get(server));
        Map<String, Object> parameters = new HashMap<String, Object>() {
            private static final long serialVersionUID = 4826028661717923632L;
            {
                put("port", Configuration.port);
                put("suites", Configuration.suites);
            }
        };
        APIHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }
    
    /**
     * Get base URI by current environment
     * @return Processed base URI
     */
    public static String getBaseUri() {
        return Configuration.getBaseUri(Servers.DEFAULT);
    }
    
    /**
     * Map of all base URLs by environments and server aliases 
     */
    private static EnumMap<Environments, EnumMap<Servers, String>> environmentsMap = new EnumMap<Environments, EnumMap<Servers,String>>(Environments.class) {
        private static final long serialVersionUID = 5756791555750570965L;
        {
            put(Environments.PRODUCTION , new EnumMap<Servers, String>(Servers.class) {
                private static final long serialVersionUID = 5602502209136162087L;
                {
                    put(Servers.DEFAULT, "http://apimatic.hopto.org:{suites}");
                    put(Servers.AUTH_SERVER, "http://apimaticauth.hopto.org:3000");
                }
            });
            put(Environments.TESTING , new EnumMap<Servers, String>(Servers.class) {
                private static final long serialVersionUID = 4683296497740595182L;
                {
                    put(Servers.DEFAULT, "http://localhost:3000");
                    put(Servers.AUTH_SERVER, "http://apimaticauth.xhopto.org:3000");
                }
            });
        }
    };
}
