# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module BaTester
  # APIController
  class APIController < BaseController
    @instance = APIController.new

    class << self
      attr_accessor :instance
    end

    def instance
      self.class.instance
    end

    # TODO: type endpoint description here
    # @return String response from the API call
    def get_basic_auth_test
      # Prepare query url.
      _query_builder = Configuration.get_base_uri
      _query_builder << '/auth/basic'
      _query_url = APIHelper.clean_url _query_builder

      # Prepare and execute HttpRequest.
      _request = @http_client.get(
        _query_url
      )
      BasicAuth.apply(_request)
      _context = execute_request(_request)
      validate_response(_context)

      # Return appropriate response type.
      _context.response.raw_body
    end
  end
end
