//
//  Configuration.h
//  BATester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef BATester_Configuration_h
#define BATester_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** extern reference to the config variable Suites */
extern NSString* Configuration_Suites;

/** The username to use with basic authentication */
/** extern reference to the config variable BasicAuthUserName */
extern NSString* Configuration_BasicAuthUserName;

/** The password to use with basic authentication */
/** extern reference to the config variable BasicAuthPassword */
extern NSString* Configuration_BasicAuthPassword;

#endif
