/*
 * BATester.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using BATester.UWP;
using BATester.UWP.Utilities; 
using BATester.UWP.Http.Client;
using BATester.UWP.Http.Response;
using BATester.Tests.Helpers;
using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
using BATester.UWP;
using BATester.UWP.Controllers;
using BATester.UWP.Exceptions;

namespace BATester.Tests
{
    [TestClass]
    public class APIControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static APIController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [TestInitialize]
        public void SetUpClass()
        {
            controller = GetClient().Client;
            applyConfiguration();
        }

        /// <summary>
        /// TODO: Add description for test TestBasicAuthTest 
        /// </summary>
        [TestMethod]
        public async Task TestBasicAuthTest() 
        {

            // Perform API call
            string result = null;

            try
            {
                result = await controller.GetBasicAuthTestAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("You've passed the test!", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

    }
}