<?php
/*
 * BATesterLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace BATesterLib;

/**
 * Baseurl aliases
 */
class Servers
{
    /**
     * TODO: Write general description for this element
     */
    const DEFAULT_ = "default";

    /**
     * TODO: Write general description for this element
     */
    const AUTH_SERVER = "auth server";
}
