//
//  SuiteCodeEnum.h
//  BATester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "SuiteCodeEnumHelper.h"

/**
* Helper class implementation for SuiteCodeEnum to NSString conversion
*/
@implementation SuiteCodeEnumHelper

+(id) stringFromSuiteCodeEnum:(enum SuiteCodeEnum) suiteCodeEnum withDefault: (id) defaultValue
{
    switch(suiteCodeEnum)
    {
        case SuiteCodeHearts:
            return @"1";

        case SuiteCodeSpades:
            return @"2";

        case SuiteCodeClubs:
            return @"3";

        case SuiteCodeDiamonds:
            return @"4";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromSuiteCodeEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [SuiteCodeEnumHelper stringFromSuiteCodeEnum:(enum SuiteCodeEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum SuiteCodeEnum) suiteCodeEnumFromString:(NSString*) strValue
{
    NSArray* SuiteCodeEnumArray = [NSArray arrayWithObjects:
                                        @"1",
                                        @"2",
                                        @"3",
                                        @"4",
                                        nil];

    return (enum SuiteCodeEnum) [SuiteCodeEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) suiteCodeEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ SuiteCodeEnumHelper suiteCodeEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end