//
//  SuiteCodeEnum.h
//  BATester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_SUITECODEENUM
#define APIMATIC_SUITECODEENUM
typedef NS_ENUM(NSInteger, SuiteCodeEnum)
{
        SuiteCodeHearts = 1, //TODO: Write general description for this method
        SuiteCodeSpades = 2, //TODO: Write general description for this method
        SuiteCodeClubs = 3, //TODO: Write general description for this method
        SuiteCodeDiamonds = 4, //TODO: Write general description for this method
};

#endif