//
//  SuiteCodeEnum.h
//  BATester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_SUITECODEENUMHELPER
#define APIMATIC_SUITECODEENUMHELPER

#include "SuiteCodeEnum.h"

/**
* Helper class interface for SuiteCodeEnum to NSString conversion
*/
@interface SuiteCodeEnumHelper : NSObject

+(id) stringFromSuiteCodeEnum:(enum SuiteCodeEnum) suiteCodeEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromSuiteCodeEnumArray:(NSArray<NSNumber*>*) array;


+(enum SuiteCodeEnum) suiteCodeEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) suiteCodeEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif